demo_bug: false
#
# 数据库设置，选择你需要使用的数据储存方式，sqlite,mysql
# 如果开启 BungeeCord 模式，子服的数据库设置将不起作用
# 默认: sqlite
data_storage:
  use_type: sqlite
  mysql:
    host: '127.0.0.1'
    port: 3306
    database: 'server_ticket'
    username: 'root'
    password: '123456ABABABC'
    params: '?autoReconnect=true&useSSL=false'
    DataName: roll_data
  hikari_settings:
    maximum_pool_size: 10
    minimum_idle: 5
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000

#
# Redis 服务器设置
# 默认不启用，如果你需要支持BC多服务器模式，则必须启用 Redis
RedisServer:
  #
  # 是否启用 BungeeCord 模式
  # 启用后，你必须链接 Redis缓存服务器
  # 默认: false
  startBungee: false
  Redis_Set:
    host: 'localhost'
    port: 6379
    password: '123456789'
    use_ssl: false

#
# 是否启用自动清空数据 - 在到达设置中的日期时，自动清除所有 月卷 数据。
# 默认: false
auto_clear: false

#
# 自动清除的日期 支持 1-31
# 默认: 1 号
auto_clear_day: 1

#
# 是否启用 全局排行榜 只适合BC模式 | 本地排行榜默认启用
# 默认: false
GlobalTop: false

#
# 是否启用自动保存数据
# 默认: false
AutoSave: false


